[tox]
env_list = py312, py313
isolated_build = True # Important for pyproject.toml based projects

[testenv]
runner = uv-venv-lock-runner # Use tox-uv's runner for lockfile-based environments
deps = pytest
commands = pytest
